
local data = {
    {
	    _id         = "1", 
	    sec			= "dev",
	    avatar 		= 101,
	    enterBattleFrame = 0,
	    level       = 1,	    
	    state 		= 1,
	    
	    userExt = {
	    	pulseNode = "1",
		},
	    	    
	    states = {
	        {
	            advId  = 0,
	            id    = 1,
	            status = 0,
	         }
	    },
	    team           = 1,   
	    treasures = {
	        ["101"] = { -- 悬挂式的还没有 铁盾
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	        -- ["102"] = { -- 悬挂式的还没有 符盾
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["103"] = { --	木剑
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["104"] = { --仙女剑
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["105"] = { -- 峨眉刺
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        ["106"] = { -- 	竹青 (正式第一版)
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	        -- ["107"] = { -- 青韵伞 
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["201"] = { -- 元龟盾 (正式第一版)
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["202"] = { -- 龙鳞盾
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        ["203"] = { -- 龙泉剑 (正式第一版)
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	        -- ["204"] = { -- 玉腰弓
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["205"] = { -- 铁八卦
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        ["206"] = { 	-- 影诛
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	        ["207"] = { -- 定魂剑 (正式第一版)
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	        	 state       = 1,
	             status      = 1,
	        },
	        -- ["209"] = { -- 锦萝伞
	             
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["210"] = { -- 寒香枫木(琴)
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["211"] = { -- 两气瓶
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["305"] = { -- 飞瀑水吟
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["306"] = { --  幽真剑
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["315"] = { -- 玄暝剑	(正式第一版)
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["317"] = { -- 松风卧云(琴)(正式第一版)
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        -- ["322"] = { -- 开元追月弓
	        --      lastUseTime = 0,
	        --      level       = 1,
	        --      star        = 1,
	        --      state       = 1,
	        --      status      = 1,
	        -- },
	        ["408"] = { -- 镇岳八卦（镜）(正式第一版)
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	        ["503"] = { -- 后羿射日弓 (正式第一版)
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	        ["507"] = { -- 幽月辰辉(伞) (正式第一版)
	             lastUseTime = 0,
	             level       = 1,
	             star        = 1,
	             state       = 1,
	             status      = 1,
	        },
	    },
        userBattleType = 1,
    },
 }

 return data