--家园系统相关事件
local GuildEvent = {}

--创建
GuildEvent.CREATE_GUILD_EVENT = "CREATE_GUILD_EVENT";
GuildEvent.CREATE_GUILD_OK_EVENT = "CREATE_GUILD_OK_EVENT";

--查询
GuildEvent.FIND_GUILD_EVENT = "FIND_GUILD_EVENT";
GuildEvent.FIND_GUILD_OK_EVENT = "FIND_GUILD_OK_EVENT";

--列表
GuildEvent.LIST_GUILD_EVENT = "LIST_GUILD_EVENT";
GuildEvent.LIST_GUILD_OK_EVENT = "LIST_GUILD_OK_EVENT";

--关闭GuildBlankView 
GuildEvent.CLOSE_GUILD_BLANK_VIEW_EVENT = "CLOSE_GUILD_BLANK_VIEW_EVENT";
GuildEvent.CLOSE_GUILD_JOIN_VIEW_EVENT = "CLOSE_GUILD_JOIN_VIEW_EVENT";


--申请加入公会
GuildEvent.GUILD_APPLY_EVENT = "GUILD_APPLY_EVENT";
GuildEvent.GUILD_APPLY_OK_EVENT = "GUILD_APPLY_OK_EVENT";

--公会成员信息
GuildEvent.GUILD_GET_MEMBERS_EVENT = "GUILD_GET_MEMBERS_EVENT";
GuildEvent.GUILD_GET_MEMBERS_OK_EVENT = "GUILD_GET_MEMBERS_OK_EVENT";

--公会申请列表
GuildEvent.GUILD_GET_APPLY_LIST_EVENT = "GUILD_GET_APPLY_LIST_EVENT";
GuildEvent.GUILD_GET_APPLY_LIST_OK_EVENT = "GUILD_GET_APPLY_LIST_OK_EVENT";

--修改公会配置
GuildEvent.GUILD_MODITY_CONFIG_EVENT = "GUILD_MODITY_CONFIG_EVENT";
GuildEvent.GUILD_MODITY_CONFIG_OK_EVENT = "GUILD_MODITY_CONFIG_OK_EVENT";

--取消公会申请
GuildEvent.GUILD_CANCEL_APPLY_EVENT = "GUILD_CANCEL_APPLY_EVENT";
GuildEvent.GUILD_CANCEL_APPLY_OK_EVENT = "GUILD_CANCEL_APPLY_OK_EVENT";

--公会成员发生变化
GuildEvent.GUILD_MEMBER_CHANGE_EVENT = "GUILD_MEMBER_CHANGE_EVENT";

--入会审批
GuildEvent.GUILD_APPLY_JUDGE_EVENT = "GUILD_APPLY_JUDGE_EVENT";
GuildEvent.GUILD_APPLY_JUDGE_OK_EVENT = "GUILD_APPLY_JUDGE_OK_EVENT";

--退出公会
GuildEvent.GUILD_KICK_GUILD_EVENT = "GUILD_KICK_GUILD_EVENT";
GuildEvent.GUILD_KICK_GUILD_OK_EVENT = "GUILD_KICK_GUILD_OK_EVENT";

--修改会员权限
GuildEvent.GUILD_MODIFY_MEMBER_RIGHT_EVENT = "GUILD_MODIFY_MEMBER_RIGHT_EVENT";
GuildEvent.GUILD_MODIFY_MEMBER_RIGHT_OK_EVENT = "GUILD_MODIFY_MEMBER_RIGHT_OK_EVENT";

--退出公会
GuildEvent.GUILD_QUIT_EVENT = "GUILD_QUIT_EVENT";
GuildEvent.GUILD_QUIT_OK_EVENT = "GUILD_QUIT_OK_EVENT";

--邀请
GuildEvent.GUILD_invite_EVENT = "GUILD_invite_EVENT";
GuildEvent.GUILD_invite_OK_EVENT = "GUILD_invite_OK_EVENT";



return GuildEvent







