--登录相关事件
local LoginEvent = {}

--登录成功
LoginEvent.LOGINEVENT_LOGIN_SUCCESS = "LOGINEVENT_LOGIN_SUCCESS"
--获取区服列表成功
LoginEvent.LOGINEVENT_GET_SERVER_LIST_OK = "LOGINEVENT_GET_SERVER_LIST_OK"
--选区发生变化
LoginEvent.LOGINEVENT_CHANGEZONE = "LOGINEVENT_CHANGEZONE"

LoginEvent.LOGINEVENT_REGIST_OK = "LOGINEVENT_REGIST_OK"

LoginEvent.LOGINEVENT_LOG_OUT = "LOGINEVENT_LOG_OUT"

--绑定账号成功
LoginEvent.LOGINEVENT_BIND_ACCOUNT_SUCCESS = "LOGINEVENT_BIND_ACCOUNT_SUCCESS"

--绑定账号失败
LoginEvent.LOGINEVENT_BIND_ACCOUNT_FAIL = "LOGINEVENT_BIND_ACCOUNT_FAIL"

--登录成功，更新model数据完成
LoginEvent.LOGINEVENT_LOGIN_UPDATE_MODEL_COMPLETE = "LOGINEVENT_LOGIN_UPDATE_MODEL_COMPLETE"

LoginEvent.LOGINEVENT_SELECT_ZONE_BACK = "LOGINEVENT_SELECT_ZONE_BACK"

return LoginEvent
