--region *.lua
--Date
--此文件由[BabeLua]插件自动生成

local TowerEvent = {}

TowerEvent.TOWERR_MODEL_UPDATE = "TOWERR_MODEL_UPDATE"
--一场战斗流程结束
TowerEvent.TOWER_EVENT_COMPLETE = "TOWER_EVENT_COMPLETE"
TowerEvent.TOWER_CAN_OPEN_BOX = "TOWER_CAN_OPEN_BOX"
TowerEvent.TOWER_OPEN_BOX_OK = "TOWER_OPEN_BOX_OK"
TowerEvent.TOWER_CAN_GET_NEW_ACHIEVEMENT = "TOWER_CAN_GET_NEW_ACHIEVEMENT"
TowerEvent.TOWER_CAN_RESET_RED_POINT = "TOWER_CAN_RESET_RED_POINT"
TowerEvent.TOWER_RECEIVE_SWEEP_REWARD_OK = "TOWER_RECEIVE_SWEEP_REWARD_OK"

--
TowerEvent.TOWERR_FLOOR_UPDATE = "TOWERR_FLOOR_UPDATE"
TowerEvent.TOWERR_RED_POINT_UPDATA = "TOWERR_RED_POINT_UPDATA"
return TowerEvent

--endregion
