--
-- Author: xd
-- Date: 2015-11-24 16:17:50
--
--法宝相关事件
local TreasureEvent = {}

TreasureEvent.PLUS_STAR_SUCCESS_EVENT = "PLUS_STAR_SUCCESS_EVENT"
TreasureEvent.ENHANCE_SUCCESS_EVENT = "ENHANCE_SUCCESS_EVENT"

TreasureEvent.REFINE_SUCCESS_EVENT = "REFINE_SUCCESS_EVENT"


--更新了UserModel的数据
TreasureEvent.TREASUREEVENT_MODEL_UPDATE = "TREASUREEVENT_MODEL_UPDATE"
TreasureEvent.TREASUREEVENT_MODEL_DELETE = "TREASUREEVENT_MODEL_DELETE"
TreasureEvent.TREASUREEVENT_MODEL_NEW = "TREASUREEVENT_MODEL_NEW"

--合成了法宝
TreasureEvent.TREASURE_COMBINE_EVENT = "TREASURE_COMBINE_EVENT"

--//更新了法宝,星耀系统使用
TreasureEvent.STARLIGHT_UPDATE_ITEM="STARLIGHT_UPDATE_ITEM"


--切换法宝
TreasureEvent.CHANGE_SELECT = "CHANGE_SELECT"

--切换回法宝
TreasureEvent.CHANGE_TREASURE = "CHANGE_TREASURE"

TreasureEvent.FABAO_YUANMAN = "FABAO_YUANMAN"

--获取碎片
TreasureEvent.FABAO_SUIPIAN = "FABAO_SUIPIAN"

--是否可以操作，升星，强化，精炼
TreasureEvent.OPERATION_STATE_CHANGE = "OPERATION_STATE_CHANGE"

--法宝有变化
TreasureEvent.TREASUREEVENT_MODEL_CHANGE ="TREASUREEVENT_MODEL_CHANGE"

TreasureEvent.CANCEL_EFFECT_LIUGUANG = "CANCEL_EFFECT_LIUGUANG"


return TreasureEvent


