--六界系统相关事件
local WorldEvent = {}

--节点成绩发生变化
WorldEvent.WORLDEVENT_CHAPTER_STAGE_SCORE_UPDATE = "WORLDEVENT_CHAPTER_STAGE_SCORE_UPDATE"

--节点成绩从非三星修变化为三星
WorldEvent.WORLDEVENT_CHAPTER_STAGE_SCORE_DELETE = "WORLDEVENT_CHAPTER_STAGE_SCORE_DELETE"

-- 额外奖励界面关闭
WorldEvent.WORLDEVENT_EXTREA_REWARD_VIEW_CLOSE = "WORLDEVENT_EXTREA_REWARD_VIEW_CLOSE"

-- 开启奇缘窗口关闭
WorldEvent.WORLDEVENT_UNLOCK_ROMANCE_CLOSE = "WORLDEVENT_UNLOCK_ROMANCE_CLOSE"

-- 关闭PVE 战斗界面
WorldEvent.WORLDEVENT_CLOSE_PVE_BATTLE = "WORLDEVENT_CLOSE_PVE_BATTLE"

-- 关闭GVE 战斗界面
WorldEvent.WORLDEVENT_CLOSE_GVE_BATTLE = "WORLDEVENT_CLOSE_GVE_BATTLE"

-- 打开star宝箱
WorldEvent.WORLDEVENT_OPEN_STAR_BOXES = "WorldEvent.WORLDEVENT_OPEN_STAR_BOXES"

-- 打开额外宝箱
WorldEvent.WORLDEVENT_OPEN_EXTRA_BOXES = "WorldEvent.WORLDEVENT_OPEN_EXTRA_BOXES"

-- 试炼小红点状态
WorldEvent.WORLDEVENT_TRAIL_RED_POINT_UPDATE = "WorldEvent.WORLDEVENT_TRAIL_RED_POINT_UPDATE"
-- 竞技场小红点状态
WorldEvent.WORLDEVENT_PVP_RED_POINT_UPDATE = "WorldEvent.WORLDEVENT_PVP_RED_POINT_UPDATE"

-- PVE战斗胜利
WorldEvent.WORLDEVENT_PVE_BATTLE_WIN = "WorldEvent.WORLDEVENT_PVE_BATTLE_WIN"

-- 关闭关卡明细界面
WorldEvent.WORLDEVENT_PVE_CLOSE_LEVEL_VIEW = "WorldEvent.WORLDEVENT_PVE_CLOSE_LEVEL_VIEW"


return WorldEvent
