--家园系统相关事件
local HomeEvent = {}

HomeEvent.GET_ONLINE_PLAYER_EVENT = "GET_ONLINE_PLAYER_EVENT";
HomeEvent.GET_ONLINE_PLAYER_OK_EVENT = "GET_ONLINE_PLAYER_OK_EVENT";
HomeEvent.GET_ONLINE_PLAYER_EVENT_AGAIN = "GET_ONLINE_PLAYER_EVENT_AGAIN";
HomeEvent.GET_ONLINE_PLAYER_EVENT_OK_AGAIN = "GET_ONLINE_PLAYER_EVENT_OK_AGAIN";

HomeEvent.RED_POINT_EVENT = "RED_POINT_EVENT";
HomeEvent.CHANGE_INAITATION_MATCH_ID_EVENT = "CHANGE_INAITATION_MATCH_ID_EVENT";

HomeEvent.HOMEEVENT_COME_BACK_TO_MAIN_VIEW = "HOMEEVENT_COME_BACK_TO_MAIN_VIEW";

HomeEvent.SHOW_HOME_VIEW = "SHOW_HOME_VIEW";
HomeEvent.OTHER_VIEW_ON_HOME = "OTHER_VIEW_ON_HOME";

HomeEvent.TELL_HOME_VIEW_ADD_NPC_HEAD_GLOW_EVENT = "TELL_HOME_VIEW_ADD_NPC_HEAD_GLOW_EVENT";

HomeEvent.CLICK_NPC_EVENT = "CLICK_NPC_EVENT";

--//走马灯消息
HomeEvent.TROT_LAMP_EVENT = "TROT_LAMP_EVENT";

HomeEvent.CHANGE_CAMERA_POSX = "CHANGE_CAMERA_POSX";

HomeEvent.SYSTEM_OPEN_EVENT = "SYSTEM_OPEN_EVENT";

return HomeEvent


