--抽卡系统相关事件
local LotteryEvent = {}

--开启cd
LotteryEvent.LOTTERYEVENT_START_CD = "LOTTERYEVENT_START_CD"

-- 关闭获取法宝界面
LotteryEvent.LOTTERYEVENT_CLOSE_TREASURE_VIEW = "LOTTERYEVENT_CLOSE_TREASURE_VIEW"

-- 展示下一个奖品
LotteryEvent.LOTTERYEVENT_SHOW_NEXT_REWARD = "LotteryEvent.LOTTERYEVENT_SHOW_NEXT_REWARD"

-- 关闭奖品界面
LotteryEvent.LOTTERYEVENT_CLOSE_REWARD_VIEW	 = "LotteryEvent.LOTTERYEVENT_CLOSE_REWARD_VIEW"

-- 再次抽卡成功
LotteryEvent.LOTTERYEVENT_DO_LOTTERY_AGAIN_SUCCESS = "LOTTERYEVENT_DO_LOTTERY_SUCCESS"

return LotteryEvent
