--//伙伴系统事件集合
--//2016-12-5 10:18:50
--//Author 狄建彬
local   PartnerEvent = PartnerEvent or {}

--某一个伙伴的信息发生了变化
PartnerEvent.PARTNER_INFO_CHANGE_EVENT = "PARTNER_INFO_CHANGE_EVENT"
--与伙伴系统相关的碎片发生了变化
PartnerEvent.PARTNER_FRAGMENT_CHANGE_EVENT = "PARTNER_FRAGMENT_CHANGE_EVENT"
--伙伴技能点发生了变化
PartnerEvent.PARTNER_SKILL_POINT_CHANGED = "PARTNER_SKILL_POINT_CHANGED"
--伙伴技能点的更新时间发生了变化
PartnerEvent.PARTNER_SKILL_POINT_UPDATE_TIME_CHANGED = "PARTNER_SKILL_POINT_UPDATE_TIME_CHANGED"
--伙伴的数目发生了变化
PartnerEvent.PARTNER_NUMBER_CHANGE_EVENT = "PARTNER_NUMBER_CHANGE_EVENT"
--某一个伙伴升级成功
PartnerEvent.PARTNER_LEVELUP_EVENT = "PARTNER_LEVELUP_EVENT"
--伙伴的星级提高
PartnerEvent.PARTNER_STAR_LEVELUP_EVENT = "PARTNER_STAR_LEVELUP_EVENT"
--星级节点发生变化
PartnerEvent.PARTNER_STAR_POINT_CHANGE_EVENT = "PARTNER_STAR_POINT_CHANGE_EVENT"
--伙伴的经验发生了变化
PartnerEvent.PARTNER_EXP_CHANGE_EVENT = "PARTNER_EXP_CHANGE_EVENT"
--伙伴品质装备位置发生变化
PartnerEvent.PARTNER_QUALITY_POSITION_CHANGE_EVENT = "PARTNER_QUALITY_POSITION_CHANGE_EVENT"
--品质发生变化
PartnerEvent.PARTNER_QUALITY_CHANGE_EVENT = "PARTNER_QUALITY_CHANGE_EVENT"
--伙伴品质道具合成
PartnerEvent.PARTNER_QUALITY_ITEM_COMBINE_EVENT = "PARTNER_QUALITY_ITEM_COMBINE_EVENT"
--伙伴的技能发生了变化
PartnerEvent.PARTNER_SKILL_CHANGED_EVENT = "PARTNER_SKILL_CHANGED_EVENT"
--伙伴的仙魂发生了变化
PartnerEvent.PARTNER_SOUL_CHANGE_EVENT = "PARTNER_SOUL_CHANGE_EVENT"
--顶部红点变化
PartnerEvent.PARTNER_TOP_REDPOINT_EVENT = "PARTNER_TOP_REDPOINT_EVENT"
return PartnerEvent
