--家园系统相关事件
local QuestEvent = {}

QuestEvent.DAILY_QUEST_CHANGE_EVENT = "DAILY_QUEST_CHANGE_EVENT";
QuestEvent.MAINLINE_QUEST_CHANGE_EVENT = "MAINLINE_QUEST_CHANGE_EVENT";
QuestEvent.QUEST_CHECK_SP_EVENT = "QUEST_CHECK_SP_EVENT";


return QuestEvent


