local SmeltEvent = {}

SmeltEvent.SMELTEVENT_SELECTE_ITEM_CHANGED = "SMELTEVENT_SELECTE_ITEM_CHANGED"
SmeltEvent.SMELTEVENT_SMELT_OK = "SMELTEVENT_SMELT_OK"
SmeltEvent.SMELTEVENT_BUY_TITLE_OK = "SMELTEVENT_BUY_TITLE_OK"
SmeltEvent.SMELTEVENT_SELECT_CANCEL= "SMELTEVENT_SELECT_CANCEL"
SmeltEvent.SMELTEVENT_SELECT_OK = "SMELTEVENT_SELECT_OK"
SmeltEvent.SMELTEVENT_ONEKEY_ADD_OK = "SMELTEVENT_ONEKEY_ADD_OK"

return SmeltEvent
