
local TrialEvent = {}

TrialEvent.BATTLE_SUCCESSS_EVENT = "BATTLE_SUCCESSS_EVENT";
TrialEvent.CLOSE_SWEEP_EVENT = "CLOSE_SWEEP_EVENT";
TrialEvent.SWEEP_BATTLE_SUCCESS_EVENT = "SWEEP_BATTLE_SUCCESS_EVENT";

return TrialEvent


