--用户系统相关事件
local TutorialEvent = {}

--界面改变
TutorialEvent.TUTORIALEVENT_VIEW_CHANGE = "TUTORIALEVENT_VIEW_CHANGE";
TutorialEvent.TUTORIALEVENT_SYSTEM_OPEN = "TUTORIALEVENT_SYSTEM_OPEN";
TutorialEvent.TUTORIALEVENT_FINISH_ALL = "TUTORIALEVENT_FINISH_ALL";

return TutorialEvent