--用户系统相关事件
local UserEvent = {}

--更新了UserModel的数据
UserEvent.USEREVENT_MODEL_UPDATE = "USEREVENT_MODEL_UPDATE"

--删除model数据
UserEvent.USEREVENT_MODEL_DELETE = "USEREVENT_MODEL_DELETE"

-- 钻石变更消息
UserEvent.USEREVENT_GOLD_CHANGE = "USEREVENT_GOLD_CHANGE"
-- 体力变更消息
UserEvent.USEREVENT_SP_CHANGE = "USEREVENT_SP_CHANGE"
-- 等级变更消息
UserEvent.USEREVENT_LEVEL_CHANGE = "USEREVENT_LEVEL_CHANGE"
--//经验发生变化
UserEvent.USEREVENT_EXP_CHANGE = "USEREVENT_EXP_CHANGE"
--vip发生改变
UserEvent.USEREVENT_VIP_CHANGE = "USEREVENT_VIP_CHANGE"

--Coin发生变化
UserEvent.USEREVENT_COIN_CHANGE="USEREVENT_COIN_CHANGE"
--竞技场货币发生变化
UserEvent.USEREVENT_PVP_COIN_CHANGE = "USEREVENT_PVP_COIN_CHANGE"
--真气发生改变
UserEvent.USEREVENT_PULSECOIN_CHANGE = "USEREVENT_PULSECOIN_CHANGE"

--战力发生变化
UserEvent.USEREVENT_PLAYER_POWER_CHANGE = "USEREVENT_PLAYER_POWER_CHANGE"

--法宝相关
UserEvent.USEREVENT_Treasure_LIST_CHANGE = "USEREVENT_Treasure_LIST_CHANGE"

--主角品阶发生了变化
UserEvent.USEREVENT_QUALITY_CHANGE = "USEREVENT_QUALITY_CHANGE"

--主界面相关
UserEvent.HOME_MAGIC_NPC_EVENT = "HOME_MAGIC_NPC_EVENT"
UserEvent.HOME_NORMAL_NPC_TRIG_EVENT = "HOME_NORMAL_NPC_TRIG_EVENT"
UserEvent.HOME_NORMAL_NPC_UPDATE_EVENT = "HOME_NORMAL_NPC_UPDATE_EVENT"

UserEvent.USEREVENT_SET_AVATAR_OK = "USEREVENT_SET_AVATAR_OK"

UserEvent.USEREVENT_NAME_CHANGE_OK = "USEREVENT_NAME_CHANGE_OK"
UserEvent.USEREVENT_SET_NAME_OK= "USEREVENT_SET_NAME_OK"

return UserEvent
